name: Build & Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Pull Foundation Image
        uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation
      
      - name: BuildDataProcessing
        run: dotnet build ./QuantConnect.DataProcessing/QuantConnect.DataProcessing.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: BuildDataSource
        run: dotnet build ./QuantConnect.DataSource/QuantConnect.DataSource.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: BuildDataSourceTests
        run: dotnet build ./QuantConnect.DataSource.Tests/QuantConnect.DataSource.Tests.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Run Tests
        run: dotnet test ./QuantConnect.DataSource.Tests/bin/Release/net6.0/QuantConnect.DataSource.Tests.dll
